#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : librttopo
Version  : 1.1.0
Release  : 1
URL      : https://git.osgeo.org/gitea/rttopo/librttopo/archive/librttopo-1.1.0.tar.gz
Source0  : https://git.osgeo.org/gitea/rttopo/librttopo/archive/librttopo-1.1.0.tar.gz
Summary  : the RT Topology library
Group    : Development/Tools
License  : GPL-2.0
Requires: librttopo-lib = %{version}-%{release}
Requires: librttopo-license = %{version}-%{release}
BuildRequires : geos-dev

%description
RT Topology Library
===================
## Build status
| OSGeo | GitLab |
|:---   |:---    |
| [![Build Status](https://dronie.osgeo.org/api/badges/rttopo/librttopo/status.svg?branch=master)] (https://dronie.osgeo.org/rttopo/librttopo?branch=master) | [![Gitlab-CI](https://gitlab.com/rttopo/rttopo/badges/master/build.svg)] (https://gitlab.com/rttopo/rttopo/commits/master) |

%package dev
Summary: dev components for the librttopo package.
Group: Development
Requires: librttopo-lib = %{version}-%{release}
Provides: librttopo-devel = %{version}-%{release}
Requires: librttopo = %{version}-%{release}

%description dev
dev components for the librttopo package.


%package lib
Summary: lib components for the librttopo package.
Group: Libraries
Requires: librttopo-license = %{version}-%{release}

%description lib
lib components for the librttopo package.


%package license
Summary: license components for the librttopo package.
Group: Default

%description license
license components for the librttopo package.


%prep
%setup -q -n librttopo
cd %{_builddir}/librttopo

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1670974398
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1670974398
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/librttopo
cp %{_builddir}/librttopo/COPYING %{buildroot}/usr/share/package-licenses/librttopo/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/librttopo.h
/usr/include/librttopo_geom.h
/usr/lib64/librttopo.so
/usr/lib64/pkgconfig/rttopo.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/librttopo.so.1
/usr/lib64/librttopo.so.1.1.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/librttopo/4cc77b90af91e615a64ae04893fdffa7939db84c
